README.md

The example does not work because the `Parser` is not imported.

Correct the code example adding the Parser class

---

README.md
tests/__init__.py
tree_sitter/__init__.py
tree_sitter/binding.c

Add methods `node.child_by_field_id` and `node.child_by_field_name`.
Also, fix a possible ref-counting bug by using the `Py_RETURN_NONE` macro.

Child by field

---

tests/test_tree_sitter.py
tree_sitter/binding.c

This PR attempts to add a few more bindings (with tests) for:
* `child_count`
* `named_child_count`
* `next_sibling`
* `prev_sibling`
* `next_named_sibling`
* `prev_named_sibling`
* `parent`
There is also a binding for `is_missing` but it lacks a test as I don't have sample source for JavaScript or Python that produces that condition.
If someone has an example of that I might be able to add a test for it.
<s>BTW, I ran the tests successfully with tree-sitter-python's `tree-sitter-cli` dev dependency in `package.json` set to something in the 0.16.x series as I failed to have the 0.17.x series (i.e. master branch) work with the tests.</s>
See below for update.

More bindings

---

tree_sitter/binding.c

Sorry, I think I introduced some leaks in https://github.com/tree-sitter/py-tree-sitter/commit/4fd0d9269c4802aa2949d410f318b1139868d8d0 in the two `node_get_*child_count` implementations.
I checked using a debug build of python and observed the reported refcounts in a python session started with `python -X showrefcount`:
Before the current PR:
```
[219100 refs, 0 blocks]
>>> list_node = exp_stmt_node.children[0]
[219107 refs, 0 blocks]
>>> list_node.child_count
7
[219108 refs, 0 blocks]
>>> list_node.child_count
7
[219109 refs, 0 blocks]
>>> list_node.child_count
7
[219110 refs, 0 blocks]
>>> list_node.child_count
7
[219111 refs, 0 blocks]
```
So the refcount has increased after `list_node.child_count` and keeps increasing.
With the changes in this PR:
```
[219096 refs, 0 blocks]
>>> …
```

Fix leaks in node_get_*child_count

---

tree_sitter/binding.c

After a little bit of investigation I noticed that `Language.language_id` was overflowing when transformed into a c `long` integer so I replaced it with a `long long`. Tests ran smoothly on my machine: Win 64 MVSC, Python 3.9. I dont know if it affects other platforms.

Fix crash on Windows 64bit

---

pyproject.toml

Explicitly declares that this project uses setuptools to build
itself.
Modern versions of pip will warn for packages that don't declare
what the expected way to build them is.
(The version of wheel pinned from below here is simply to avoid
a macOS 11 bug in wheel).

Add a pyproject.toml

---

tree_sitter/binding.c

PyTuple_Pack will do a Py_INCREF on it's arguments, so we need to Py_DECREF on them here. 
Closes #49

Fix leaks in point_new

---

tree_sitter/binding.c

`PyList_GetItem` returns a borrowed reference to the list element that
is then passed to `PyTuple_Pack`, which increments its reference count
and stores that reference in the tuple. Calling `Py_XDECREF` on the
reference therefore leaves the refcount one too low.
<details><summary>Run of test suite on commit 36536ed23169ecb7ace1497d2eca01db12e211fb</summary>
This uses CPython v3.9.1 compiled with `--with-assertions --with-address-sanitizer --with-undefined-behavior-sanitizer --with-valgrind --with-pydebug --enable-shared`, but it also affects the CPython interpreter from the Arch repos (also v3.9.1).
```
============================================================ test session starts ============================================================
platform linux -- Python 3.9.1, pytest-6.2.2, …
```

Fix use after free of `Query.capture_names` elements

---

tree_sitter/binding.c

`PyObject_GetAttrString` returns a new reference that was never
decref’d.
This fixes the memory leak that can be seen here: https://github.com/tree-sitter/py-tree-sitter/pull/52#issuecomment-778637186
<details><summary>Run of test suite with ASan with the fix</summary>
```
============================================================ test session starts ============================================================
platform linux -- Python 3.9.1, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /tmp/py-tree-sitter
collected 11 items
tests/test_tree_sitter.py ...........
============================================================ 11 passed in 7.35s ============================================================
```
</details>

Fix memory leak in `Parser.set_language`

---

.github/workflows/ci.yml
tree_sitter/__init__.py

When a tree sitter grammar contains a `scanner.cc` file, a C++ standard
library must be linked to the final grammar shared object. `distutils`
uses the default `cc` compiler driver to compile and link C and C++
files. On Linux, this is GCC, so `libstdc++` must be linked, even if
`libc++` is present.
On Mac, `libc++` is the default, even if `libstdc++` is present.
Use the `c++` compiler driver for linking, so that the appropriate standard library
is selected automatically.
----
This PR also adds CI for Mac (as well as Ubuntu and Windows) using GitHub actions.
Resolves #43, resolves #41, resolves #27.

Fix Linux build with libcxx present

---

tests/test_tree_sitter.py
tree_sitter/binding.c

This PR attempts to finish the work started by @sogaiu in PR #37 to address issue #36. 
A summary of the features implemented in this PR:
- `.text` preoperty can be accessed on tree and node objects, which will return the source code of the object as bytes
- `.text` returns `None` if the tree has been edited (present in the original PR)
- `.text` accesses the source code using MemoryViews to avoid copying the data when slicing (present in the original PR, though a tweak has been added to obtain the desired behavior)
- `parser_parse()` has now an optional (keyword) parameter `keep_text` (as suggested in https://github.com/tree-sitter/py-tree-sitter/pull/37#issuecomment-703305527). When setting it to `False`, no source code will be stored in the tree object and `.text` will return `None`. …

Add text property to tree and node objects

---

tests/test_tree_sitter.py
tree_sitter/binding.c

This PR adds support for predicates in queries, which resolves #22. I have tried to replicate the same overall steps performed by the Rust bindings (whenever possible), as it seemed reasonable and that it would help keep some coherence between the bindings.
Here is summary of the changes implemented in this PR:
- If a text predicate is present in a query, results are filtered according to it. The supported operators are #eq?, #not-eq?, #match? and #not-match? (other operators are ignored and will not affect the result of the query)
- Basic tests for these operators have been added
- The Query object has two new attributes: `string_values` (a list of all the parsed strings of the query) and `text_predicates` (a list of all text predicates of the query)
- New PyObject types have been …

Query predicates

---

README.md
tests/test_tree_sitter.py
tree_sitter/binding.c

Extend the Parser.parse() method to take a callable which acts like the
"read" callback from a TSInput struct. This callable takes the requested
byte offset and source location and returns a bytes object corresponding
to the source at that location. Returning an empty bytes object or None
terminates parsing for that line.
It is assumed that the parser only needs to "borrow" the return value
from the TSInput's read callback until the next call to the function or
when the ts_parser_parse() function returns. As such we use the
"payload" of the TSInput structure to record the last bytes object
returned so that its reference count may be decremented on the next call
to the read callback or when ts_parser_parse() returns.
Add some basic tests which demonstrate using the byte offset and TSPoint …

add support for TSInput-style parsing

---

tests/test_tree_sitter.py
tree_sitter/binding.c

This PR includes:
* an attempt to add a `named_children` binding
* some associated tests
* some tweaks to `node_get_children` regarding checking of some return values
<s>Unlike `node_get_children`, `node_get_named_children` doesn't check or interact with the "cache" of `children`: https://github.com/tree-sitter/py-tree-sitter/blob/323d2bb0e26d7b9ac816b562fb38cbec9138ff18/tree_sitter/binding.c#L11 within `Node`.  I suppose it could...</s>
See update below.

Named children

---

tree_sitter/binding.c

I noticed this small inconsistency while using tree_sitter. bug or feature?
```
<Node kind=expression_statement, start_point=(0, 0), end_point=(0, 38)>
ipdb> node.type
'expression_statement'
ipdb> node.kind
*** AttributeError: 'tree_sitter.Node' object has no attribute 'kind'
```

Use consistent attribute names in repr

---

tests/test_tree_sitter.py
tree_sitter/binding.c

Added bindings for ts_node_field_name_for_child function.
https://github.com/tree-sitter/tree-sitter/blob/6192d2961096bda537e8ecb20de9c9dbd506cad8/lib/include/tree_sitter/api.h#L501

Added field_name_for_child method

---

tests/test_tree_sitter.py
tree_sitter/binding.c

Hey all,
Thanks for the library! I'd like to contribute something that I've wanted a few times when working with py-tree-sitter.
As a note, I'm not very well-versed in C or writing Python extensions, so although this seems pretty simple, a critical eye would be appreciated.
This PR adds a `__hash__` method to the Node class. This makes it possible to add Node instances to sets or use them as dictionary keys. I've tested and found the hash to work well and be consistently the same for a given node, and consistently different for different nodes as you'd expect.

Add __hash__ method to Node

---

tree_sitter/__init__.py

Importing `distutils` takes more than 90% of the total import time of `tree_sitter`, but it is only used when compiling new languages. The common case should not need to pay for that.
Some measurements:
Without this PR:
```console
$ python -Ximporttime -c 'import tree_sitter'
import time: self [us] | cumulative | imported package
[...]
import time:       613 |        613 |         json.encoder
import time:       347 |       2441 |       json
import time:      2406 |     129771 |     distutils
import time:       513 |     130284 |   distutils.ccompiler
import time:       444 |        444 |     shlex
import time:       176 |        176 |       distutils.py39compat
import time:       168 |        168 |       distutils._functools
import time:       927 |       1269 |     distutils.sysconfig …
```

Move `distutils` import into `Language.build_library`

---

.github/workflows/ci.yml
.github/workflows/pypi.yml
README.md
pyproject.toml
script/lint
setup.py
tests/test_tree_sitter.py
tree_sitter/__init__.py
tree_sitter/binding.c
tree_sitter/binding.pyi

Hello!
`distutils` was removed in Python 3.12, burt is included in setuptools 48+.
We might want to add setuptools to the requirements for Python, maybe as extra?
I'm open for discussion for better ways to add 3.12 support :) 
Have a nice day!

fix: 3.12 removed distutils, add fallback to setuptools

---

tests/test_tree_sitter.py
tree_sitter/binding.c

If a predicate in a query references a capture that was not matched because it was optional in the query, return true rather than throw an error. In other words, if the capture was not found, ignore the predicate entirely.
This matches the behavior of tree-sitter CLI and the playground. It is not a common case but we have run into the issue matching Kotlin functions where the return type of a function is optional in the grammar requiring us to do additional filtering in the app code after the query.

Make predicate with missing capture return true

---

tree_sitter/binding.pyi

The .pyi file for the bindings report that Tree.text is a str but it is bytes. This was [fixed](https://github.com/tree-sitter/py-tree-sitter/commit/f246d063f8699ebce3aab9cf957447cb8db098e4) for Node.text but not for for Tree.

Fix type of Tree.text property

---

tree_sitter/binding.c

Formerly, calling `node.get_children_by_field_name("not_defined_field_name")` or `node.get_children_by_field_id(0)` would return a list of _unnamed_ child nodes. Now, it returns an empty list. This fixes #97

get_children_by_field_id and get_children_by_field_name returns empty list on invalid argument

---

tests/test_tree_sitter.py
tree_sitter/_binding.pyi
tree_sitter/binding.c

Return the captures of a match as a dict where the key is the capture name and the value is a Node or a list of Nodes. For regular captures, the value is a Node. For captures that can contain multiple nodes because they use a * or + quantifier, the value is a list of Nodes.
---
Closes #182

Make match captures a dict[str,Node|list[Node]]

---

README.md
tests/test_parser.py
tree_sitter/__init__.pyi
tree_sitter/binding/parser.c

`utf8` / `utf16` are preferred by any valid alias is supported.
Closes #204 & closes #211

feat(parser): support UTF-16 encoding

---

tree_sitter/binding/query_predicates.c

Closes #308 
The condition for iterating in `satisfies_eq_capture` was wrong, it should not iterate for whichever amount between the length of the first node array and the length of the second node array is larger. It should take the shortest length, since both must be valid.
In the condition, set `l` to the shortest number between `size1` and `size2`. This mimics the Rust code [here](https://github.com/tree-sitter/tree-sitter/blob/d3a127a48fe8ec2c1552f82f6b25621e69d46140/lib/binding_rust/lib.rs#L2782)

fix(query): iterate over captures for the shortest size, not longest

---

tree_sitter/binding/query.c
tree_sitter/binding/query_predicates.c

- Closes #325
In query initialization when creating predicates, the capture_id is never set for the any of predicate, leading to issues in cases where garbage data was used for the capture id, because the match would always fail then. Also, the logic for satisfying any-of predicates seems incorrect, it asserts that for all nodes, all values of the predicate must equal the node's text, which seems incorrect.
- Set the capture id in query initialization
- Have the logic of `satisfies_anyof` be "for all nodes, assert that *any* of the predicate values equal the node's text" (not all)

any-of fixes

---

tests/test_parser.py
tree_sitter/__init__.pyi
tree_sitter/binding/parser.c

Currently `Parser.parse` can take either a single buffer as source or a callable that returns a byte string, but not a callable that returns a `memoryview`/`bytearray`.
This extends the `Parser.parse` method to take any callable that returns a simple buffer.

Support callables that return simple buffers as input for Parser.parse

---

tree_sitter/binding/node.c

This PR fixes `node_child_with_descendant` using the wrong type when parsing its arguments using `PyArg_ParseTuple`.
Previously calling this method caused undefined behavior resulting in crashes on my machine.

Fix incorrect types in node_child_with_descendant

---

tree_sitter/binding/tree.c

Follow up to #381.
Adds copying of missing fields `language` and `source` in `tree_copy`.

Fix tree_copy missing language and source fields

---

docs/classes/tree_sitter.QueryCursor.rst
docs/index.rst

I was reading the docs and couldn't find a way to the `QueryCursor` page. Previous ci logs actually warned about this page being isolated:
```
... docs/classes/tree_sitter.QueryCursor.rst: WARNING: document isn't included in any toctree [toc.not_included]
```
By the way, the heading of the page was `Query` instead of `QueryCursor`.
This pull request updates the documentation to include the `QueryCursor` class and corrects a heading mismatch in its documentation file.
Documentation updates:
* [`docs/classes/tree_sitter.QueryCursor.rst`](diffhunk://#diff-bd98119c6deb15ff71a57da09ea986d4a683a08ff5a5db685b86b6567ad534abL1-R1): Corrected the heading from "Query" to "QueryCursor" to match the class name.
* [`docs/index.rst`](diffhunk://#diff-8d068e8797e88947c320f79e856c3e16a72b730124a8f9d7031e2c …

fix(docs): QueryCursor page was missing from index

---

tree_sitter/binding/query.c
tree_sitter/binding/query_predicates.c
tree_sitter/binding/types.h

When a generic predicate callable is used, the documented signature indicates that the third argument should be the pattern index. Unfortunately, the value that was being passed was an index into an internal array of only the patterns containing predicates, not the true index of the pattern. This made it impossible for a custom directive to store information into the relevant `pattern_settings` dict (similar to how the built-in `#set!` directive does).
This change fixes that by storing the pattern index into the `QueryPredicateGeneric` structure, and then plumbing that through to the predicate callable.

fix: pattern_index parameter to generic predicates is incorrect

---

tree_sitter/binding/query_cursor.c

Fix a missing space in the hint for the `QueryCursor.captures` method.
https://tree-sitter.github.io/py-tree-sitter/classes/tree_sitter.QueryCursor.html#tree_sitter.QueryCursor.captures
(Sorry I would have included this in my last PR if I'd spotted it before!)

docs(query_cursor): fix missing space in hint
